### ISSUE TITLE
Developing Home Page

### ISSUE THREAD

**Issue by nickydime** [BradWalsh97/SlightlyDelayedGram#21]
Development of front end - crucial to being able to view posts and the rest of the main page.
Development includes:

- Navigation bar, and it's included re directional buttons
- Overall style of the web page.
- A picture feed prioritizing followed content first

This issue is a sub story of: [#4]

**Comment by nickydime** [comment]
Preliminary portion has been completed (mostly cosmetic for now).

**Comment by NihlathakTheNecromancer** [comment]
Hey Nick, so to fit the format of issues to date you should assign the "Sub-task" label to the issue and then go to the "Posting a Picture" Story and reference this issue. This is done to keep track of what needs to be accomplished to say that our user story is complete (and allowing us to remove pending story points from the sprint). Besides that, maybe have a one or two sentence description of what the task requires to be done, how it will be done and then if there is any progress you can comment what you've done in detail. This is so that if (for some reason) you can't complete the task, someone can pick up the task where you left off and can understand what has already been accomplished. I will also post this in Discord so that everyone sees because it could be helpful.

Thanks!
